#!/bin/sh

ssh -t -t -o StrictHostKeyChecking=no root@`cat ip.txt` <<EOF
  cd /home/charlie-jackson-website
  sudo apt-get -y install python-pip
  sudo pip install docker-compose
  docker-compose up -d --force-recreate --build
  exit
EOF
