#!/bin/sh

ERR=1 # or some non zero error number you want

x=1
while [ $x -le 20 ]
do
   echo "Attempt at ./scripts/prep-droplet-ssh"
   ./scripts/prep-droplet-ssh `cat ip.txt`

   if [ "$?" -eq "0" ]; then
     echo "Successfully ran ./scripts/prep-droplet-ssh"
     exit 0
   fi

   echo "Failed attempt at ./scripts/prep-droplet-ssh"
   sleep 3
   x=$(( $x + 1 ))
done

echo "COULD NOT RUN ./scripts/prep-droplet-ssh"
exit $ERR
