#!/bin/sh

ssh root@178.62.88.113 <<EOF
  sudo apt-get -y update
  cd /home
  git clone -b develop --recursive https://github.com/cajacko/charlie-jackson-website.git
  cd /home/charlie-jackson-website
  echo "MYSQL_ROOT_PASSWORD=testpassword" >> .env
  echo "MYSQL_DATABASE=testdatabase" >> .env
  echo "MYSQL_USER=testuser" >> .env
  echo "MYSQL_PASSWORD=testpassword" >> .env
  exit
EOF
